[package]
name = "adventofcode"
version = "0.1.0"
authors = ["Spyridon Pagkalos <spyridon@ender.gr>"]
edition = "2018"

[dependencies]
regex = "1"

[[bin]]
name = "dec01"
path = "src/dec01.rs"

[[bin]]
name = "dec02"
path = "src/dec02.rs"

[[bin]]
name = "dec03"
path = "src/dec03.rs"
